name: mymikano_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    # Base
  cupertino_icons: ^1.0.3
  nb_utils: ^4.2.11
  cached_network_image: ^3.0.0
  flutter_svg: ^0.22.0
  html: ^0.15.0
  intl: ^0.17.0
  mobx: ^2.0.1
  carousel_slider: ^4.0.0-nullsafety.0
  dots_indicator: ^2.0.0
  flutter_mobx: ^2.0.0
  showcaseview: ^1.0.0
  flutter_spinkit: "^5.0.0"
  oauth2: ^2.0.0
  path_provider: ^2.0.2
  fluttertoast: ^8.0.7
  sizer: ^2.0.13
  http: ^0.13.3
  transparent_image: ^2.0.0
  multi_image_picker: ^4.8.00
  graphql_flutter: ^5.0.0
  share: ^2.0.4
  rflutter_alert: ^2.0.2
  audioplayers: ^0.19.1
  flutter_audio_recorder2: ^0.0.2
  permission_handler: ^8.1.4+1
  flutter_launcher_icons: ^0.9.1
  connectivity: ^3.0.6
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  cloud_firestore: ^2.5.1
  firebase_messaging: ^10.0.6
  provider: ^6.0.0
  flutter_dotenv: ^5.0.2
  flutter_switch: ^0.3.2
  syncfusion_flutter_gauges: ^19.2.59

#  flutter_absolute_path:
#    git:
#      url: https://github.com/kornperkus/flutter_absolute_path.git
# flutter_absolute_path: ^1.0.6
# The following adds the Cupertino Icons font to your application.
# Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/theme5/logo-circle.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/theme5/
    - images/LikeButton/image/grey.jpg
    - .env

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
